export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";
export const POST_PROJECTS_REQUEST = "POST_PROJECTS_REQUEST";
export const POST_PROJECTS_SUCCESS = "POST_PROJECTS_SUCCESS";
export const POST_PROJECTS_ERROR = "POST_PROJECTS_ERROR";
export const DELETE_PROJECTS_REQUEST = "DELETE_PROJECTS_REQUEST";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_ERROR = "DELETE_PROJECTS_ERROR";



